# Generated by Django 3.0.7 on 2020-09-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gyro', 'Gyro'), ('motion', 'Motion'), ('position', 'Position'), ('temperature', 'Temperature'), ('barometric', 'Barometric')], help_text='Enter the measurement category', max_length=32)),
                ('name', models.CharField(help_text='Enter instrument name.', max_length=32)),
                ('location', models.CharField(help_text='Enter instrument location.', max_length=32, null=True)),
                ('position1', models.IntegerField(null=True, unique=True)),
                ('position2', models.IntegerField(null=True, unique=True)),
                ('position3', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_instrument', to='instrument.Instrument')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_time', to='instrument.TimeData')),
            ],
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easting', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('northing', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('height', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_instrument', to='instrument.Instrument')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_time', to='instrument.TimeData')),
            ],
        ),
        migrations.CreateModel(
            name='MotionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('roll', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('heave', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_instrument', to='instrument.Instrument')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motion_time', to='instrument.TimeData')),
            ],
        ),
        migrations.CreateModel(
            name='GyroData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.DecimalField(decimal_places=3, max_digits=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyro_instrument', to='instrument.Instrument')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gyro_time', to='instrument.TimeData')),
            ],
        ),
        migrations.CreateModel(
            name='BarometricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barometric', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barometric_instrument', to='instrument.Instrument')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barometric_time', to='instrument.TimeData')),
            ],
        ),
    ]
