# Generated by Django 3.0.7 on 2020-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='position1',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='position2',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='position3',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
