# Generated by Django 3.0.7 on 2020-10-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_auto_20200929_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
