# Generated by Django 3.0.7 on 2020-10-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0004_auto_20201008_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gyrodata',
            old_name='time',
            new_name='datetime',
        ),
    ]
